#!/bin/bash

# if no parameter is passed, display usage and exit
if [ -z "$1" ]; then
	echo "Usage: $0 <symlink>"
	exit 1
fi

item=$1

# make sure item is a symlink in the current directory
if [ ! -L "$item" ]; then
	echo "Error: $item is not a symlink"
	exit 1
fi

cp -pL $item $item-copy
rm -f $item
mv $item-copy $item

echo "Resolved symlink $item into a copy of the target file"
echo